pipeline:
  name: Build Harnessdemo
  identifier: Build_vvtilak_Harnessdemo_1708668221755
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
              - step:
                  type: Run
                  name: snyk_test
                  identifier: snyk_test
                  spec:
                    connectorRef: docker_connection
                    image: vvtilak:helo-world
                    shell: Sh
                    command: |-
                      snyk config set api=$SNYK_TOKEN
                      snyk test
                    envVariables:
                      snyk_token: ce4cfa62-a268-4a72-a9a1-d15e1c9daaef
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1708668196530
        repoName: vvtilak/sample_harenss_demo
        build: <+input>
